version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: taskmanagement_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskmanagment_db
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: 12345
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: